# Generated by Django 5.2.10 on 2026-01-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='remaining_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fees',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
